/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import IniciarSesion.RegistrarUsuario;
import Preferencias.Preferencias;
import Utilidades.Seguridad;
import basedatos.ListaUsuarios;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.net.InetAddress;
import java.net.Socket;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;

/**
 *
 * @author anfur
 */
public class EditarPreferencias extends javax.swing.JFrame {

    private String id;
    private Preferencias pref;
    private Seguridad s = new Seguridad();
    private Socket server;
    private InetAddress ip;
    private String admin;
    private ListaUsuarios amigos;
    private ListaUsuarios usuariosMismasPrefs;

    /**
     * Creates new form EditarPreferencias
     */
    public EditarPreferencias() {
        initComponents();
    }

    /**
     * Creates new form EditarPreferencias
     */
    public EditarPreferencias(String id) {
        this.id = id;
        initComponents();
    }
    
    /**
     * Creates new form EditarPreferencias
     */
    public EditarPreferencias(String id,String admin) {
        this.id = id;
        this.admin = admin;
        initComponents();
    }
    
    /**
     * Creates new form EditarPreferencias
     */
    public EditarPreferencias(String id,String admin,ListaUsuarios amigos, ListaUsuarios usuariosMismasPrefs) {
        this.id = id;
        this.amigos = amigos;
        this.admin = admin;
        this.usuariosMismasPrefs = usuariosMismasPrefs;
        initComponents();
    }
    
    //

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbGustos = new javax.swing.JComboBox<>();
        spDeportivo = new javax.swing.JSpinner();
        spArtistico = new javax.swing.JSpinner();
        spPolitico = new javax.swing.JSpinner();
        cbRelacionSeria = new javax.swing.JComboBox<>();
        cbHijos = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Relación seria");

        jLabel2.setText("Deportivo");

        jLabel3.setText("Artísticos");

        jLabel4.setText("Politicos");

        jLabel5.setText("Tiene/Quiere hijos");

        jLabel6.setText("Gustos en");

        cbGustos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chico", "Chica", "Ambos" }));

        spDeportivo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        spArtistico.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        spPolitico.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        cbRelacionSeria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relación seria", "Relación esporádica" }));

        cbHijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiene hijos", "Quiere hijos", "Ninguna" }));

        btnGuardar.setText("Guardar preferencias");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRelacionSeria, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbGustos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbHijos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spPolitico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(spArtistico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spDeportivo, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRelacionSeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spDeportivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spPolitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbGustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PantallaPrincipal v = new PantallaPrincipal(id,admin,amigos,usuariosMismasPrefs);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        int idUsuario = Integer.parseInt(id);
        boolean relacionSeria = false;
        boolean tieneHijos = false;
        boolean quiereHijos = false;
        boolean interesMujer = false;
        boolean interesHombre = false;
        boolean interesAmbos = false;
        int deportivo;
        int artistico;
        int politico;
        if (cbRelacionSeria.getSelectedItem().toString().equals("Relación seria")) {
            relacionSeria = true;
        } else {
            relacionSeria = false;
        }

        if (cbHijos.getSelectedItem().toString().equals("Tiene hijos")) {
            tieneHijos = true;
        }

        if (cbHijos.getSelectedItem().toString().equals("Quiere hijos")) {
            quiereHijos = true;
        }

        deportivo = (int) spDeportivo.getValue();
        artistico = (int) spArtistico.getValue();
        politico = (int) spPolitico.getValue();

        String interesHombreMujerAmbos = cbGustos.getSelectedItem().toString();

        if (interesHombreMujerAmbos.equals("")) {
            interesMujer = true;
        }

        if (interesHombreMujerAmbos.equals("")) {
            interesHombre = true;
        }

        if (interesHombreMujerAmbos.equals("")) {
            interesAmbos = true;
        }

        pref = new Preferencias(idUsuario, relacionSeria, deportivo, artistico, politico, tieneHijos,quiereHijos, interesHombre,interesMujer,interesAmbos);

        //System.out.println(pref);
        try {
            KeyPairGenerator KeyGen = KeyPairGenerator.getInstance("RSA");
            KeyGen.initialize(2048);
            KeyPair par = KeyGen.generateKeyPair();
            PrivateKey clavepriv = par.getPrivate();
            PublicKey clavepubl = par.getPublic();
            ip = InetAddress.getLocalHost();
            server = new Socket(ip, 1234);
            ObjectOutputStream oos = new ObjectOutputStream(server.getOutputStream());
            DataInputStream datos = new DataInputStream(server.getInputStream());
            DataOutputStream dos = new DataOutputStream(server.getOutputStream());
            PrintStream ps = new PrintStream(server.getOutputStream());
            String editarPreferencias = "editarPreferencias";
            String respuesta;
            
            KeyGenerator kg = KeyGenerator.getInstance("AES");
            kg.init(128);
            SecretKey claveSimetrica = kg.generateKey();

            //ps.println("");
            dos.writeUTF("");
            //ps.println(editarPreferencias);
            dos.writeUTF(editarPreferencias);
            RegistrarUsuario mensaje = new RegistrarUsuario();
            
            mensaje.setClaveSimetrica(claveSimetrica);

            oos.writeObject(mensaje);

            Cipher c = Cipher.getInstance("AES/ECB/PKCS5Padding");
            c.init(Cipher.ENCRYPT_MODE, claveSimetrica);
            
            //Preferencias pref2 = new Preferencias(1);
            
            //Creamos un objeto encapsulado con el cipher creado anteriormente y el objeto que queremos encapsular (tiene que implementar serializable)
            SealedObject sealedObject = new SealedObject(pref, c);

            oos.writeObject(sealedObject);

            //datos.readLine();
            //respuesta = datos.readLine();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbGustos;
    private javax.swing.JComboBox<String> cbHijos;
    private javax.swing.JComboBox<String> cbRelacionSeria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner spArtistico;
    private javax.swing.JSpinner spDeportivo;
    private javax.swing.JSpinner spPolitico;
    // End of variables declaration//GEN-END:variables
}
