/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import IniciarSesion.Mensaje;
import Utilidades.Seguridad;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author anfur
 */
public class Registro2 extends javax.swing.JFrame {

    private Seguridad s = new Seguridad();
    private Socket server;
    private InetAddress ip;
    private byte[]imagen;

    /**
     * Creates new form Registro2
     */
    public Registro2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrarse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioRegistro = new javax.swing.JTextField();
        pwdContrasenaRegistro = new javax.swing.JPasswordField();
        btnAceptarRegistro = new javax.swing.JButton();
        btnVolverRegistro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNickRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreRegistro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnElegirImagen = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Correo");

        jLabel2.setText("Password");

        btnAceptarRegistro.setText("Aceptar");
        btnAceptarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRegistroActionPerformed(evt);
            }
        });

        btnVolverRegistro.setText("Volver");
        btnVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroActionPerformed(evt);
            }
        });

        jLabel4.setText("Nick");

        jLabel5.setText("Nombre");

        txtNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRegistroActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido");

        jLabel7.setText("Foto");

        btnElegirImagen.setText("Elegir imagen");
        btnElegirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrarseLayout = new javax.swing.GroupLayout(pnlRegistrarse);
        pnlRegistrarse.setLayout(pnlRegistrarseLayout);
        pnlRegistrarseLayout.setHorizontalGroup(
            pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                        .addComponent(btnAceptarRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElegirImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverRegistro)
                        .addGap(52, 52, 52))
                    .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                        .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                                    .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(54, 54, 54)
                                    .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pwdContrasenaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(txtUsuarioRegistro)))
                                .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                                    .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(61, 61, 61)
                                    .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtApellidoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(txtNickRegistro)
                                        .addComponent(txtNombreRegistro))))
                            .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(81, 81, 81)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlRegistrarseLayout.setVerticalGroup(
            pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdContrasenaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                        .addComponent(txtNickRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(pnlRegistrarseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarRegistro)
                    .addComponent(btnElegirImagen)
                    .addComponent(btnVolverRegistro))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRegistroActionPerformed
        try {
            ip = InetAddress.getLocalHost();
            server = new Socket(ip, 1234);
            KeyGenerator kg = KeyGenerator.getInstance("AES");
            kg.init(128);
            SecretKey claveSimetrica = kg.generateKey();
            ObjectOutputStream oos = new ObjectOutputStream(server.getOutputStream());
            PrintStream ps = new PrintStream(server.getOutputStream());
            String registro = "Registro";
            Mensaje registrarse = new Mensaje();
            String usuario = txtUsuarioRegistro.getText().toString();
            String clave = pwdContrasenaRegistro.getText().toString();
            String nick = txtNickRegistro.getText().toString();
            String nombre = txtNombreRegistro.getText().toString();
            String apellido = txtApellidoRegistro.getText().toString();
            byte[] foto;

            byte[] usuarioCifrado;
            byte[] claveResumida = s.resumirMensaje(clave);
            byte[] nickCifrado;
            byte[] nombreCifrado;
            byte[] apellidosCifrado;
            byte[] fotoCifrada;

            nickCifrado = s.cifrarMensaje(nick, claveSimetrica);
            usuarioCifrado = s.cifrarMensaje(usuario, claveSimetrica);
            nombreCifrado = s.cifrarMensaje(nombre, claveSimetrica);
            apellidosCifrado = s.cifrarMensaje(apellido, claveSimetrica);
            //fotoCifrada = s.cifrarMensaje(foto, claveSimetrica);

            registrarse.setCorreo(usuarioCifrado);
            registrarse.setClaveResumida(claveResumida);
            registrarse.setNickCifrado(nickCifrado);
            registrarse.setNombreCifrado(nombreCifrado);
            registrarse.setApellidoCifrado(apellidosCifrado);
            //registrarse.setFotoCifrada(fotoCifrada);
            
            registrarse.setClaveSimetrica(claveSimetrica);

            ps.println("");
            ps.println(registro);

            oos.writeObject(registrarse);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAceptarRegistroActionPerformed

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        Login p = new Login();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void txtNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRegistroActionPerformed

    private void btnElegirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirImagenActionPerformed
        JFileChooser fc = new JFileChooser();

//        FileFilter logFilefilter = new FileFilter() {
//
//            public boolean accept(File file) {
//
//                if (file.getName().endsWith(".png") || file.getName().endsWith(".jpg")) {
//                    return true;
//                }
//                return false;
//            }
//
//            @Override
//            public String getDescription() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//        };

        fc.setDialogTitle("Buscar imagen");
        //fc.setFileFilter(logFilefilter);

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = fc.getSelectedFile();
            String origen = archivo.getPath();
            ImageIcon icon = new ImageIcon(new ImageIcon(origen).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            try {
                DataInputStream dis = new DataInputStream(new FileInputStream(archivo));
                imagen = new byte[(int) archivo.length()];
                dis.readFully(imagen);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Registro2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Registro2.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblImagen.setIcon(icon);
        }

    }//GEN-LAST:event_btnElegirImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRegistro;
    private javax.swing.JButton btnElegirImagen;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel pnlRegistrarse;
    private javax.swing.JPasswordField pwdContrasenaRegistro;
    private javax.swing.JTextField txtApellidoRegistro;
    private javax.swing.JTextField txtNickRegistro;
    private javax.swing.JTextField txtNombreRegistro;
    private javax.swing.JTextField txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
